export const DELETE_CHAT = "DELETE_CHAT";
export const ADD_CHAT = "ADD_CHAT";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const ADD_MESSAGE_FROM_BOT = "ADD_MESSAGE_FROM_BOT";
export const INCREASE_COUNT = "INCREASE_COUNT";
export const DECREASE_COUNT = "DECREASE_COUNT";
